--- manifests-example.local/node-exporter-daemonset.yaml	2021-04-23 13:56:19.000000000 +0200
+++ ../deploy/prometheus/node-exporter-daemonset.yaml	2021-04-23 13:52:42.000000000 +0200
@@ -43,13 +43,13 @@
             memory: 180Mi
         volumeMounts:
         - mountPath: /host/sys
-          mountPropagation: HostToContainer
+          # mountPropagation: HostToContainer
           name: sys
           readOnly: true
-        - mountPath: /host/root
-          mountPropagation: HostToContainer
-          name: root
-          readOnly: true
+        # - mountPath: /host/root
+        #   mountPropagation: HostToContainer
+        #   name: root
+        #   readOnly: true
       - args:
         - --logtostderr
         - --secure-listen-address=[$(IP)]:9100
@@ -91,9 +91,9 @@
       - hostPath:
           path: /sys
         name: sys
-      - hostPath:
-          path: /
-        name: root
+      # - hostPath:
+      #     path: /
+      #   name: root
   updateStrategy:
     rollingUpdate:
       maxUnavailable: 10%
